// assets/utils/signal/HomeEvents.ts
export const HOME_EVENTS = {
    // 初始化阶段
    INIT_START: 'HOME_INIT_START',
    INIT_CORE_UI_READY: 'HOME_INIT_CORE_UI_READY',
    INIT_ESSENTIAL_DATA_READY: 'HOME_INIT_ESSENTIAL_DATA_READY',
    INIT_ALL_DATA_READY: 'HOME_INIT_ALL_DATA_READY',

    // UI相关
    UI_CORE_SHOW: 'HOME_UI_CORE_SHOW',
    UI_SECONDARY_SHOW: 'HOME_UI_SECONDARY_SHOW',
    UI_HUD_SHOW: 'HOME_UI_HUD_SHOW',
    UI_SCREEN_RESIZE: 'HOME_UI_SCREEN_RESIZE',

    // 数据相关
    DATA_CURRENCY_UPDATED: 'HOME_DATA_CURRENCY_UPDATED',
    DATA_LEVEL_UPDATED: 'HOME_DATA_LEVEL_UPDATED',
    DATA_HERO_UPDATED: 'HOME_DATA_HERO_UPDATED',

    // 关卡相关
    LEVEL_INIT_START: 'HOME_LEVEL_INIT_START',
    LEVEL_INIT_COMPLETE: 'HOME_LEVEL_INIT_COMPLETE',
    LEVEL_CHANGE_START: 'HOME_LEVEL_CHANGE_START',
    LEVEL_CHANGE_COMPLETE: 'HOME_LEVEL_CHANGE_COMPLETE',

    // 资源加载
    LOAD_ESSENTIAL_START: 'HOME_LOAD_ESSENTIAL_START',
    LOAD_ESSENTIAL_COMPLETE: 'HOME_LOAD_ESSENTIAL_COMPLETE',
    LOAD_LAZY_START: 'HOME_LOAD_LAZY_START',
    LOAD_LAZY_PROGRESS: 'HOME_LOAD_LAZY_PROGRESS',
    LOAD_LAZY_COMPLETE: 'HOME_LOAD_LAZY_COMPLETE',

    // 音频相关
    AUDIO_INIT_COMPLETE: 'HOME_AUDIO_INIT_COMPLETE',
    AUDIO_MUSIC_PLAY: 'HOME_AUDIO_MUSIC_PLAY',

    // 本地化
    LOCALIZATION_INIT_COMPLETE: 'HOME_LOCALIZATION_INIT_COMPLETE',
    LOCALIZATION_CHANGE: 'HOME_LOCALIZATION_CHANGE',

    // 性能监控
    PERFORMANCE_WARNING: 'HOME_PERFORMANCE_WARNING',
    PERFORMANCE_REPORT: 'HOME_PERFORMANCE_REPORT',

    // 按钮事件
    BUTTON_START_CLICK: 'HOME_BUTTON_START_CLICK',
    BUTTON_LEVEL_PREV_CLICK: 'HOME_BUTTON_LEVEL_PREV_CLICK',
    BUTTON_LEVEL_NEXT_CLICK: 'HOME_BUTTON_LEVEL_NEXT_CLICK',
    BUTTON_HERO_CLICK: 'HOME_BUTTON_HERO_CLICK',
    BUTTON_TALENT_CLICK: 'HOME_BUTTON_TALENT_CLICK',
    BUTTON_SETTINGS_CLICK: 'HOME_BUTTON_SETTINGS_CLICK',
    BUTTON_SPEED_BOOST_CLICK: 'HOME_BUTTON_SPEED_BOOST_CLICK',
    BUTTON_DAMAGE_BOOST_CLICK: 'HOME_BUTTON_DAMAGE_BOOST_CLICK',
} as const;

export type HomeEventType = typeof HOME_EVENTS[keyof typeof HOME_EVENTS];